services:
  - type: web
    name: backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y openjdk-17-jre
      pip install -r requirements.txt
    startCommand: cd utils && python grammerapi.py
